server:
  port: 8081
spring:
  application:
    name: SB-CRUD-API
  datasource:
    url: jdbc:mysql://localhost:3306/product_db
    username: root
    password: Suhfi07
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
